spring:
  profiles:
    active:
    - dev
---
spring:
 profies: dev #开发环境
 application:
    name: microservicecloud-conifg-dev

---
spring:
 profies: test #测试环境
 application:
    name: microservicecloud-conifg-test     